protected/modules/articles/models/Article.php
<?php

class Article extends ActiveRecordModel
{
    const PAGE_SIZE = 10;

    public function name()
    {
        return 'Статьи';
    }


    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['FileManager'] = array(
            'class' => 'application.components.activeRecordBehaviors.AttachmentBehavior',
            'attached_model' => 'FileManager'
        );

        return $behaviors;
    }


	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}


	public function tableName()
	{
		return 'articles';
	}
	
	
	public function scopes() 
	{
		return array(
			'last'   => array('order' => 'date DESC'),
		);
	}
	

	public function rules()
	{
		return array(
			array('title, text, section_id, lang', 'required'),
			array('date', 'type', 'type' => 'date', 'dateFormat' => 'dd.mm.yyyy'),
			array('title', 'length', 'max' => 400),
			array('title, text, date, date_create', 'safe', 'on' => 'search'),
		);
	}


	public function relations()
	{
		return array(
            'section'  => array(self::BELONGS_TO, 'ArticleSection', 'section_id'),
			'language' => array(self::BELONGS_TO, 'Language', 'lang')
		);
	}


	public function search()
	{
		$criteria = new CDbCriteria;
		$criteria->compare('title', $this->title, true);
		$criteria->compare('text', $this->text, true);
		$criteria->compare('date', $this->date, true);
		$criteria->compare('date_create', $this->date_create, true);

		return new ActiveDataProvider(get_class($this), array(
			'criteria' => $criteria
		));
	}
	
	
	public function beforeSave() 
	{
		if (parent::beforeSave()) 
		{
			if (!$this->date) 
			{
				$this->date = date("Y-m-d");
			}
			
			return true;
		}
	}


    public function getContent()
    {
        if (RbacModule::isAllow('ArticleAdmin_Update'))
        {
            $this->text.= "<br/> <a href='{$this->updateUrl}' class='admin_link'>Редактировать</a>";
        }

        return $this->text;
    }


    public function getUpdateUrl()
    {
        return "/articles/articleAdmin/update/id/{$this->id}";
    }
}

protected/modules/articles/controllers/ArticleController.php
<?php

class ArticleController extends BaseController 
{   
    const PAGE_SIZE = 10;


    public static function actionsTitles() 
    {
        return array(
            "Index"           => "Просмотр списка статей",
            "View"            => "Просмотр статьи",
            "Search"          => "Поиск статей",
            "SectionArticles" => "Просмотр статей раздела"
        );
    }    
    
    
    public function actionIndex() 
    {
        $model = Article::model();

        $criteria = $model->dbCriteria;     
        $criteria->order = 'date DESC';

        $pages = new CPagination($model->count($criteria));
        $pages->pageSize = self::PAGE_SIZE;
        $pages->applyLimit($criteria);
            
        $articles = $model->findAll($criteria);    

		$sections = ArticleSection::model()->findAllByAttributes(
			array('parent_id' => null),
			array('order' => 'name')
		);	       	
     
        $this->render('index', array(
            'articles' => $articles,
			'sections' => $sections,
            'pages'    => $pages
        ));      
    }
    
    
    public function actionView($id) 
    {   
        $article = Article::model()->findByPk($id); 
        if (!$article) 
        {
            $this->pageNotFound();
        }
        
        $this->render('view', array('article' => $article));
    }
    
    
    public function actionSearch() 
    {       
        if (!$this->request->isAjaxRequest) 
        {   
            return;
        }
        
        $criteria = new CDbCriteria();
      
        if (isset($_POST['section_id'])) 
        {   
            $section = ArticleSection::model()->findByPk((int) $_POST['section_id']);   
       
            if (!$section) 
            {  
                return;
            }
            
            $secttion_ids = array($section->id);  
            
            if ($section->childs) 
            {
                foreach ($section->childs as $child) 
                {
                    $secttion_ids[] = $child->id;
                }
            }  
            
            $criteria->addInCondition("section_id", $secttion_ids);                     
        }      
        
        if (isset($_POST['query'])) 
        {
            $query = $_POST['query'];    
            
            $criteria->addCondition("`title` LIKE '%{$query}%' OR `text` LIKE '%{$query}%'"); 
        }
      
        $articles = Article::model()->findAll($criteria, array('order' => 'date DESC', 'limit' => 10));
        
        if ($articles) 
        {
            $html = $this->renderPartial('application.modules.articles.views.article._list', array('articles' => $articles), true);
            
            if (isset($section)) 
            {
                $url = $this->url("/articles/section/{$section->id}");

                $html.= "<br/><br/>
                         <div style='text-align:center'>
                            <a href='{$url}'>Все материалы данного раздела</a>
                         </div>
                         <br/>";
            } 
            
            echo $html;       
        }
        else 
        {           
            if (isset($section) && isset($query)) 
            {
                $url = $this->url("/articles/section/{$section->id}");
                $msg = "В разделе <a class='link_13' href='{$url}'>{$section->name}</a>
                        по запросу '{$query}' ничего не найдено.
                        <br/><br/>
                        Попробуйте <a href='#' id='search_link'>осущест$urlить поиск по всей Базе знаний.</a>";
            }
            elseif (isset($section)) 
            {
                $url = $this->url("/articles/section/{$section->id}");
                $msg = "В разделе <a class='link_13' href='{$url}'>{$section->name}</a>
                        ничего не найдено.";                
            }
            else if (isset($query)) 
            {
                $msg = "по запросу '{$query}' ничего не найдено.";                
            }
            
            echo $msg;
        }
    }  
    
    
    public function actionSectionArticles($section_id) 
    {  
        $section = ArticleSection::model()->findByPk($section_id);
        if (!$section) 
        {
            $this->pageNotFound();
        }
            
        $section_ids = array($section->id);    
           
        if ($section->childs) 
        {
            foreach ($section->childs as $child) 
            {
                $section_ids[] = $child->id;    
            }
        }   
        
        $section_ids = implode(',', $section_ids);
            
        $model = Article::model();
        
        $criteria = $model->dbCriteria;
        $criteria->condition = "section_id IN ({$section_ids})";
        $pages = new CPagination($model->count($criteria));
        $pages->pageSize = self::PAGE_SIZE;
        $pages->applyLimit($criteria);
        
        $articles = $model->findAll($criteria);
        
        $this->render('SectionArticles', array(
            'articles' => $articles,
            'section'  => $section,
            'pages'    => $pages
        ));
    }  
}

protected/modules/articles/views/article/SectionArticles.php
<?php 
if (!$articles) 
{
    echo $this->msg(Yii::t('ArticlesModule.main', 'Не найдены материалы данного раздела'), 'info');
}

if (!$this->crumbs) 
{
    $this->crumbs = array(
            "/"         => Yii::t('ArticlesModule.main', 'Главная'),
            "/articles" => Yii::t('ArticlesModule.main', 'База знаний')
    );
    
    if ($section->parent) 
    {
        $this->crumbs["/articles/section/{$section->parent->id}"] = $section->parent->name;
    }
    
    $this->crumbs[""] = $section->name;
}

$this->page_title = Yii::t('ArticlesModule.main', 'База знаний');
?>


<?php $this->renderPartial('application.modules.articles.views.article._list', array('articles' => $articles)); ?>    
    
<?php $this->renderPartial('application.views.layouts.pagination', array('pages' => $pages)); ?>

protected/modules/articles/views/article/_list.php
<?php foreach ($articles as $article): ?>   
    <div class="search_list">
            <!--<div class="add_favour">
                <span class="favour_star"></span>
                <a href="">добавить в избранное</a>
            </div>-->
            <a href="<?php echo $this->url("/articles/{$article->id}"); ?>" class="search_title">
                <?php echo $article->title; ?>
            </a>
            <p>
			    <?php echo Text::cut($article->text, 250, ' ', '...'); ?>
            </p>
            <a href="<?php echo $this->url("/articles/{$article->id}"); ?>" class="more_info">
                <?php echo Yii::t('ArticlesModule.main', 'Подробнее'); ?>
            </a>
     </div>	              
<?php endforeach ?>

protected/modules/articles/views/article/index.php
<?php
Yii::app()->clientScript->registerScriptFile('/js/site/articles.js');

if (!$articles) 
{
    echo $this->msg(Yii::t('ArticlesModule.main', 'Не найдены материалы данного раздела'), 'info');
}

if (!$this->crumbs) 
{
    $this->crumbs = array(
        $this->url("/")         => Yii::t('ArticlesModule.main', 'Главная'),
        $this->url("/articles") => Yii::t('ArticlesModule.main', 'База знаний')
    );
}

$this->page_title = Yii::t('ArticlesModule.main', 'База знаний');
?>

<?php if ($sections): ?>
    <?php $this->beginWidget('system.web.widgets.CClipWidget', array('id' => 'articles_search')); ?>
        <div id="ex_search">
            <form action="">
                <table border="0" width="100%">
                    <tr valign='top'>
                        <td>
                            <select class="ex_select" id="sections_select">
                                <option><?php echo Yii::t('ArticlesModule.main', 'выбор категории'); ?></option>
                                <?php foreach ($sections as $section): ?>
                                    <option value='<?php echo $section->id; ?>'><?php echo $section->name; ?></option>
                                <?php endforeach ?>
                            </select>
                        </td>
                        <td>
                            <input type="text" value="<?php echo Yii::t('ArticlesModule.main', 'Ищете что то еще?'); ?>" class="ex_text" id="article_query" />
                        </td>
                        <td>
                            <input type="button" value="<?php echo Yii::t('ArticlesModule.main', 'Найти'); ?>" class="ex_search_button" id="article_search_button" />
                        </td>
                    </tr>
                    <tr valign='top'>
                        <td>
                            <select class="ex_select" id="subsections_select">
                                <option><?php echo Yii::t('ArticlesModule.main', 'выбор подкатегории'); ?></option>
                            </select>
                        </td>
                        <td style="text-align:center">
                            <img src='/images/site/loader.gif' id="img_loader" border='0'/>
                        </td>
                    </tr>
                </table>
            </form>
        </div><br/>
    <?php $this->endWidget();?>
<?php endif; ?>

<div id="articles_content">
        
    <?php $this->renderPartial('application.modules.articles.views.article._list', array('articles' => $articles)); ?>    
        
    <?php $this->renderPartial('application.views.layouts.pagination', array('pages' => $pages)); ?>

</div>


protected/modules/articles/views/article/view.php
<?php 
$this->page_title = $article->title;

$this->crumbs = array(
	$this->url("/")         => Yii::t('ArticlesModule.main', 'Главная'),
	$this->url("/articles") => Yii::t('ArticlesModule.main', 'База знаний')
);

if ($article->section->parent) 
{
    $this->crumbs[$this->url("/articles/section/{$article->section->parent['id']}")] = $article->section->parent->name;
}

$this->crumbs[$this->url("/articles/section/{$article->section['id']}")] = $article->section->name;

?>

<?php echo $article->content; ?>

<?php if ($article->files): ?>
	<div style="margin-top:30px;margin-bottom:10px;font-weight:bold"><?php echo Yii::t('ArticlesModule.main', 'Файлы для скачивания'); ?>:</div>

	<?php foreach ($article->files as $file): ?>
		<a href='/' class='link_13'><?php echo $file->file ?></a> <br/>
	<?php endforeach ?>
<?php endif ?>



